### ISSUE TITLE
Item in cart does not update when added again

### ISSUE THREAD

**Issue by satyam1024** [DharshiBalasubramaniyam/ice-cream-parlour-website#15]
Description: When a user tries to add an item to the cart that is already present, the quantity in the cart does not update. Instead, a message is displayed saying, "The item is already in your cart!" However, the expected behavior is that the quantity of the item in the cart should increase instead of showing this message.

Steps to reproduce:
Open the ice cream selection page.
Add an item  to the cart.
Attempt to add the same item again.
Observe that the item is not updated in the cart, and a message is shown.

Expected behavior: The quantity of the item in the cart should be updated when the same item is added again, rather than displaying an alert.

Screenshots: 
![Screenshot (2994)](https://github.com/user-attachments/assets/a7ef883d-2a8c-41d4-b2bc-785005479ed4)

I'd love to work on this issue. I request you to assign it to me . Thank you!

**Comment by bjamre13** [comment]
My approach to solve the above issue is....
1.Modify Frontend Logic to Update Quantity: Change the "Add to Cart" function in the frontend to first check if the item already exists in the cart. If found, increment the quantity; if not, add the item with a quantity of 1.

2.Update Backend API Logic (If API-driven): If the cart is managed by the backend, modify the API to handle item updates. Send a request to update the quantity rather than adding the item again.

Kindly assign me this issue.

**Comment by AkankshaSinghK** [comment]
My approach to solve the above issue is....
1. Identify the item in the cart: Check whether the item already exists in the cart.
2. Update the quantity: If the item exists, increase its quantity instead of displaying the alert.
3. Add new item if it’s not present: If the item is not in the cart, add it to the cart.

Kindly assign me this issue.

**Comment by DharshiBalasubramaniyam** [comment]
Hi @satyam1024, thank you for creating this issue. Carry on. All the best.

If possible, if item is already in the cart display "already in the cart-add again?" in the button as below.

![17278393954898280024045706752296](https://github.com/user-attachments/assets/5638ec11-2df5-4dff-bf3b-ab161f54c6d9)

**Comment by satyam1024** [comment]
I would like to apologize for the accidental pull request. 
Could you please confirm if this is the look you were aiming for?
I have update the addtocart function to increase the no of product if it already exist
![Screenshot (2995)](https://github.com/user-attachments/assets/719d8f7e-ebb6-4061-a32b-e5477f18deb2)
